apiVersion: v1
kind: Service
metadata:
  name: water-quality-backend-service
spec:
  selector:
    app: water-quality-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort