"""Create initial tables

Revision ID: 0e54cb65e54d
Revises: 95703ed8be2e
Create Date: 2025-06-04 16:28:44.667804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e54cb65e54d'
down_revision = '95703ed8be2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MonitoringStations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('WaterQualityParameters',
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('safe_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safe_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('parameter_id')
    )
    op.create_table('Alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['WaterQualityParameters.parameter_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['MonitoringStations.station_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('Measurements',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['WaterQualityParameters.parameter_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['MonitoringStations.station_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'operator'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['Alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Measurements')
    op.drop_table('Alerts')
    op.drop_table('WaterQualityParameters')
    op.drop_table('MonitoringStations')
    # ### end Alembic commands ###
